### PR TITLE
PDF preview component

### PR DESCRIPTION
**Pull request by rezkiy37**
### Details

This is a PR where we introduce a MVP version of `react-fast-pdf` package. The package codebase itself has a basic configuration to read and preview a _PDF_ file. The `example` has a basic template how to use the package. 

### Related Issues

https://github.com/Expensify/App/issues/22998

### Manual Tests

1. Clone the repo.
2. Install deps. for both **package** and **example**: `npm install && cd example && npm install && cd ..`.
3. Run a script - `cd example && npm run start && cd ..` - of the **example**.
4. Verify that **Webpack** launches successfully.
5. Verify that it opens a tab.
6. Verify that the PDF previewer works. 

### Linked PRs
N/A

Screenshot 2023-09-20 at 19 51 08

https://github.com/Expensify/react-fast-pdf/assets/57314631/c73dfb1d-1194-4a80-9129-40460d981b33

### CODE REVIEW

**Comment by rezkiy37** [comment]
I have read the CLA Document and I hereby sign the CLA.

**Comment by rezkiy37** [comment]
By the way, I've tried to connect the package to the **Expensify** (_**NewDot**_) app. It works.

https://github.com/Expensify/react-fast-pdf/assets/57314631/4fdaec1a-58b2-4972-b31d-73c1b10716ce


https://github.com/Expensify/react-fast-pdf/assets/57314631/15d28f82-49b1-4e61-875f-3409e1026e29

**Comment by rezkiy37** [comment]
@allroundexperts, how can we move forward?

**Comment by rezkiy37** [comment]
> @rezkiy37 Do we have any issue to track the publishing of this package to npm?

Who can help us from the Expensify team with access to their **NPM**?

**Review by mountiny — APPROVED** [review]
Thanks, I can move it ahead and hopefully we can get the npm setup here soon

**Pull request merged**
