### PR TITLE
Fix single pdfs view styling on mWeb

### PR DESCRIPTION
**Pull request by abzokhattab**
### Related Issues

https://github.com/Expensify/App/issues/37724

### Manual Tests

1. Upload a single-page pdf.
2. Tap on the PDF preview to open it.
3. Verify it is displayed centered in the middle in mobile view. 

### Linked PRs

Referenced PR: https://github.com/Expensify/App/pull/38883

### CODE REVIEW

**Comment by abzokhattab** [comment]
I have read the CLA Document and I hereby sign the CLA

recheck

**Comment by abzokhattab** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by abzokhattab** [comment]
recheck

**Comment by Beamanator** [comment]
@mollfpr is also planning to review this, but maybe they don't have access to this repo?

**Comment by mollfpr** [comment]
Got the repo cloned with the branch PR setup!

**Comment by abzokhattab** [comment]
just a kindly reminder on this

**Review by mollfpr — APPROVED** [review]
LGMT 👍 

@Beamanator Any specific checklist on this PR?

**Review by Beamanator — APPROVED** [review]

**Comment by Beamanator** [comment]
Hmm yeah I'll need to figure out soon if we will have to publish a new version of this lib, then use that in App repo

**Comment by Beamanator** [comment]
ooh new version may be published here: https://github.com/Expensify/react-fast-pdf/actions/runs/8555795444/job/23443994988

so @abzokhattab can you please create an App PR to bump this library's version number once that is ready, then we will test using the standard checklist in App?

**Comment by Beamanator** [comment]
Looks like v1.0.9 has our changes - https://github.com/Expensify/react-fast-pdf/pull/21

**Comment by mollfpr** [comment]
@abzokhattab Could you check the E/App with `react-fast-pdf` latest version? It seems not working well on the PDF preview. I remember it was looks good when I test this PR.

Screenshot 2024-04-10 at 23 06 03

**Pull request merged**
