### PR TITLE
Dynamically update container height

### PR DESCRIPTION
**Pull request by bernhardoj**
### Details

The container height is only initialized once. This PR updates it so it dynamically updates.

### Related Issues

https://github.com/Expensify/App/issues/42566

### Manual Tests

1. Send a pdf to any chat
2. (mobile) Focus on the composer to bring up the keyboard
3. Press the PDF to open the attachment preview
4. Verify the PDF has full height

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/Expensify/react-fast-pdf/assets/50919443/c0c9c7d0-2d1b-417a-9743-2750eb01658a

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/Expensify/react-fast-pdf/assets/50919443/c561a496-6ce3-4b50-8643-3395f37d6d5b

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/Expensify/react-fast-pdf/assets/50919443/3a9893aa-9646-4463-adcd-01dfa388bdb6

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/Expensify/react-fast-pdf/assets/50919443/0f1c0eb3-bdc0-498c-941c-a330a8043652

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/react-fast-pdf/assets/50919443/ad70b1ca-583f-4841-a464-0c690e9f18d8

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/Expensify/react-fast-pdf/assets/50919443/8c359229-c9ae-431f-ae6c-09cf77161be4

</details>

### CODE REVIEW

**Comment by bernhardoj** [comment]
**_I have read the CLA Document and I hereby sign the CLA_**

**Review by mountiny — APPROVED** [review]

**Comment by mountiny** [comment]
@bernhardoj @mkhutornyi sorry lint is failing now

**Comment by bernhardoj** [comment]
@mountiny Lint fixed

**Review by mountiny — APPROVED** [review]

**Comment by rezkiy37** [comment]
**BUG:** https://expensify.slack.com/archives/C01GTK53T8Q/p1726452873116639

**Pull request merged**
